# =======================================================
# ОБЩИЕ СЕРВИСЫ ДЛЯ ВСЕХ ПРОЕКТОВ
# =======================================================
# Запуск: docker compose -f infrastructure.yml up -d

services:

  # Traefik - общий reverse proxy для всех проектов
  traefik:
    container_name: ${INFRA_NAME}-traefik
    image: traefik:3.3
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --certificatesResolvers.letsEncrypt.acme.httpChallenge=true
      - --certificatesResolvers.letsEncrypt.acme.httpChallenge.entryPoint=http
      - --certificatesResolvers.letsEncrypt.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.letsEncrypt.acme.storage=/certs/acme.json
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certs
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.http-catchall.rule=HostRegexp(`.+`)
      - traefik.http.routers.http-catchall.entryPoints=http
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectScheme.permanent=true

  # Общая MariaDB для всех проектов (опционально)
  shared-mariadb:
    profiles: ["shared-db"]
    image: mariadb:10.6
    container_name: ${INFRA_NAME}-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SHARED_DB_ROOT_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "${SHARED_DB_PORT}:3306"
    volumes:
      - shared-mariadb-data:/var/lib/mysql
      - ./mariadb/init-shared.sql:/docker-entrypoint-initdb.d/init-shared.sql:ro
    networks:
      - shared-services
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max-connections=200

  # phpMyAdmin для общей БД
  shared-phpmyadmin:
    profiles: ["shared-db"]  
    image: phpmyadmin:latest
    platform: linux/amd64
    container_name: ${INFRA_NAME}-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${INFRA_NAME}-mariadb
      PMA_USER: root
      PMA_PASSWORD: ${SHARED_DB_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: https://pma.shared.local/
      UPLOAD_LIMIT: 64M
    networks:
      - traefik-public
      - shared-services
    depends_on:
      - shared-mariadb
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.shared-pma.rule=Host(`pma.shared.local`)
      - traefik.http.routers.shared-pma.entryPoints=https
      - traefik.http.routers.shared-pma.tls=true
      - traefik.http.routers.shared-pma.tls.certResolver=letsEncrypt

  # Общий Redis (опционально)
  shared-redis:
    profiles: ["shared-cache"]
    image: redis:7-alpine
    container_name: ${INFRA_NAME}-redis
    restart: unless-stopped
    ports:
      - "${SHARED_REDIS_PORT}:6379"
    volumes:
      - shared-redis-data:/data
    networks:
      - shared-services
    command: redis-server --appendonly yes

  # MailHog для тестирования email
  mailhog:
    profiles: ["mailhog"]
    image: mailhog/mailhog:latest
    container_name: ${INFRA_NAME}-mailhog
    restart: unless-stopped
    ports:
      - "${MAILHOG_HTTP_PORT}:8025"
      - "${MAILHOG_SMTP_PORT}:1025"
    networks:
      - traefik-public
      - shared-services
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.mailhog.rule=Host(`mail.local`)
      - traefik.http.routers.mailhog.entryPoints=https
      - traefik.http.routers.mailhog.tls=true
      - traefik.http.routers.mailhog.service=mailhog
      - traefik.http.services.mailhog.loadBalancer.server.port=8025

# ✅ ИСПРАВЛЕНО: Внешние сети (созданы вручную)
networks:
  traefik-public:
    external: true
  shared-services:
    external: true

volumes:
  traefik-certs:
    name: traefik-certs
  shared-mariadb-data:
    name: shared-mariadb-data
  shared-redis-data:
    name: shared-redis-data
